// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIwymjMVa9ZNBCeM8KWmXYgjRUUxKoJw',
    appId: '1:664783266369:web:f769352e81c7409b71dcc0',
    messagingSenderId: '664783266369',
    projectId: 'mobile-plts-afif',
    authDomain: 'mobile-plts-afif.firebaseapp.com',
    storageBucket: 'mobile-plts-afif.firebasestorage.app',
    measurementId: 'G-71PV19035W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3cKNjzzZNRmzNzaz2akOCiWBeo8TEi8s',
    appId: '1:664783266369:android:1add15019717a8ce71dcc0',
    messagingSenderId: '664783266369',
    projectId: 'mobile-plts-afif',
    storageBucket: 'mobile-plts-afif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXeMJZIpY9Kye6-2f80Fb0sEVFFdd9yWs',
    appId: '1:664783266369:ios:72155327ebfbeec371dcc0',
    messagingSenderId: '664783266369',
    projectId: 'mobile-plts-afif',
    storageBucket: 'mobile-plts-afif.firebasestorage.app',
    iosBundleId: 'com.example.monitoringPlts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXeMJZIpY9Kye6-2f80Fb0sEVFFdd9yWs',
    appId: '1:664783266369:ios:72155327ebfbeec371dcc0',
    messagingSenderId: '664783266369',
    projectId: 'mobile-plts-afif',
    storageBucket: 'mobile-plts-afif.firebasestorage.app',
    iosBundleId: 'com.example.monitoringPlts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuIwymjMVa9ZNBCeM8KWmXYgjRUUxKoJw',
    appId: '1:664783266369:web:7ef105fca136ada471dcc0',
    messagingSenderId: '664783266369',
    projectId: 'mobile-plts-afif',
    authDomain: 'mobile-plts-afif.firebaseapp.com',
    storageBucket: 'mobile-plts-afif.firebasestorage.app',
    measurementId: 'G-S8RFEET4RB',
  );

}